config: Show yaml diff when comparing objects
Previously we logged using %+v format, which is very verbose but not
helpful for detecting changes. Now we show diff of object YAML.

Example run before:

    % go test -v ./pkg/config
    ...
    === RUN   TestSample
        config_test.go:26: expected &{CommandName:ramenctl HubKubeconfig:hub/config
        PrimaryKubeconfig:primary/config SecondaryKubeconfig:secondary/config
        RBDStorageClassName:rook-ceph-block-X CephFSStorageClassName:rook-cephfs-fs1}, got
        &{CommandName:ramenctl HubKubeconfig:hub/config PrimaryKubeconfig:primary/config
        SecondaryKubeconfig:secondary/config RBDStorageClassName:rook-ceph-block
        CephFSStorageClassName:rook-cephfs-fs1}
    --- FAIL: TestSample (0.00s)

Example run after:

    % go test -v ./pkg/config
    ...
    === RUN   TestSample
        config_test.go:28: sample mismatch
            --- expected
            +++ actual
            @@ -2,5 +2,5 @@
             CommandName: ramenctl
             HubKubeconfig: hub/config
             PrimaryKubeconfig: primary/config
            -RBDStorageClassName: rook-ceph-block-X
            +RBDStorageClassName: rook-ceph-block
             SecondaryKubeconfig: secondary/config
    --- FAIL: TestSample (0.00s)

Signed-off-by: Nir Soffer <nsoffer@redhat.com>