validate: Show yaml diff when comparing objects
If comparing application or clusters status fail, we used to show both
the expected value and the actual value for inspection. Finding the
difference between large texts is practically impossible so working with
the tests was very painful.

Now we show a diff between the expected and the actual value, which
makes it very easy to find the issue.

We also always logged the expected yaml for manual inspection. This is
not needed now.

Example runs after introducing few bugs:

    % go test -v ./pkg/validate -run TestValidateClustersOcp
    === RUN   TestValidateClustersOcp

    🔎 Validate config ...
       ✅ Config validated

    🔎 Validate clusters ...
       ✅ Gathered data from cluster "hub"
       ✅ Gathered data from cluster "prsurve-s2-c1"
       ✅ Gathered data from cluster "prsurve-s2-c2"
       ✅ Clusters validated

    ✅ Validation completed (37 ok, 0 stale, 0 problem)
        command_test.go:1843: clusters statuses not equal
            --- expected
            +++ actual
            @@ -141,7 +141,7 @@
                   conditions:
                   - state: ok ✅
                     type: Progressing
            -      - state: problem ❌
            +      - state: ok ✅
                     type: Available
                   deleted:
                     state: ok ✅
    --- FAIL: TestValidateClustersOcp (0.02s)
    FAIL
    FAIL	github.com/ramendr/ramenctl/pkg/validate	0.710s
    FAIL

    % go test -v ./pkg/validate -run TestValidateApplicationPassed
    === RUN   TestValidateApplicationPassed

    🔎 Validate config ...
       ✅ Config validated

    🔎 Validate application ...
       ✅ Inspected application
       ✅ Gathered data from cluster "hub"
       ✅ Gathered data from cluster "dr1"
       ✅ Gathered data from cluster "dr2"
       ✅ Application validated

    ✅ Validation completed (21 ok, 0 stale, 0 problem)
        command_test.go:1826: application statuses not equal
            --- expected
            +++ actual
            @@ -7,7 +7,7 @@
                   type: Available
                 - state: ok ✅
                   type: PeerReady
            -    - state: problem ❌
            +    - state: ok ✅
                   type: Protected
                 deleted:
                   state: ok ✅
    --- FAIL: TestValidateApplicationPassed (0.02s)
    FAIL
    FAIL	github.com/ramendr/ramenctl/pkg/validate	0.717s
    FAIL

Signed-off-by: Nir Soffer <nsoffer@redhat.com>